-- Borrar datos
BEGIN
    EXECUTE IMMEDIATE 'DELETE FROM reviews';
    EXECUTE IMMEDIATE 'DELETE FROM viajes';
    EXECUTE IMMEDIATE 'DELETE FROM servicios_destinos';
    EXECUTE IMMEDIATE 'DELETE FROM servicios';
    EXECUTE IMMEDIATE 'DELETE FROM disponibilidades';
    EXECUTE IMMEDIATE 'DELETE FROM franjas_horarias';
    EXECUTE IMMEDIATE 'DELETE FROM tarifas';
    EXECUTE IMMEDIATE 'DELETE FROM conductor_vehiculos';
    EXECUTE IMMEDIATE 'DELETE FROM vehiculos';
    EXECUTE IMMEDIATE 'DELETE FROM tarjetas_credito';
    EXECUTE IMMEDIATE 'DELETE FROM puntos_geograficos';
    EXECUTE IMMEDIATE 'DELETE FROM ciudades';
    EXECUTE IMMEDIATE 'DELETE FROM usuarios';
    COMMIT;
END;
/