-- Usuarios
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE usuarios_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE usuarios_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Ciudades
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE ciudades_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE ciudades_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Vehículos
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE vehiculos_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE vehiculos_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Franjas Horarias
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE franjas_horarias_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE franjas_horarias_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Puntos Geográficos
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE puntos_geograficos_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE puntos_geograficos_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Servicios
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE servicios_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE servicios_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Servicios Destinos
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE servicios_destinos_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE servicios_destinos_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Tarifas
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE tarifas_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE tarifas_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Viajes
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE viajes_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE viajes_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Reviews
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE reviews_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE reviews_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Tarjetas de Crédito
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE tarjetas_credito_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE tarjetas_credito_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
