-- Secuencias para IDs autogenerados

-- Usuarios
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE usuarios_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE usuarios_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- Ciudades
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE ciudades_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE ciudades_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- Vehiculos
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE vehiculos_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE vehiculos_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- FranjaHoraria
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE franjas_horarias_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE franjas_horarias_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- PuntoGeografico
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE puntos_geograficos_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE puntos_geograficos_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- Servicio
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE servicios_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE servicios_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- ServicioDestino
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE servicios_destinos_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE servicios_destinos_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- Tarifa
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE tarifas_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE tarifas_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- Viaje
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE viajes_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE viajes_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- Review
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE reviews_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE reviews_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- TarjetaCredito
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE tarjetas_credito_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE tarjetas_credito_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
